server:
  port: 9010
spring:
  application:
    name: @pom.artifactId@
  profiles:
    active: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
security:
  user:
    name: admin
    password: admin