server:
  port: 9001
spring:
  application:
    name: sunshine-provider-uac
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 127.0.0.1
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
security:
  oauth2:
    resource:
      filter-order: 3
      id: sunshine-resouce-uac
sunshine:
  security:
    oauth2:
      tokenStore: jwt
      clients[0]:
        clientId: admin
        clientSecret: 123456
        accessTokenValidateSeconds: 7200
        scope: "*"
mybatis:
  type-aliases-package: com.sunshine.provider.model.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

mapper:
  mappers: com.sunshine.core.mybatis.MyMapper
  not-empty: false
  identity: MYSQL