server:
  port: 9001
spring:
  application:
    name: sunshine-provider-uac
  redis:
    host: 127.0.0.1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
security:
  oauth2:
    resource:
      filter-order: 3
      id: sunshine-resouce-uac
sunshine:
  security:
    oauth2:
      tokenStore: jwt
      clients[0]:
        clientId: admin
        clientSecret: 123456
        accessTokenValidateSeconds: 7200
        scope: "*"
