server:
  port: 9002
spring:
  application:
    name: @pom.artifactId@
#  redis:
#    host: 127.0.0.2
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useSSL=false
    username: root
    password: root
  profiles:
    active: dev
#    driver-class-name: com.mysql.jdbc.Driver
#  zipkin:
#    sender:
#      type: rabbit
#  sleuth:
#    sampler:
#      percentage: 1.0
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#security:
#  oauth2:
#    client:
#      clientId: sofmit-client
#      clientSecret: sofmit_secret
#      access-token-uri: http://localhost:9000/uac/oauth/token
#      user-authorization-uri: http://localhost:9000/uac/oauth/authorize
#    resource:
#      user-info-uri: http://localhost:9000/uac/user
#      jwt:
#        key-uri: http://localhost:9000/uac/oauth/token_key
#sunshine:
#  oauth2:
#    client:
#      id: sunshine-resouce-uac
#      accessTokenUrl: http://localhost:9000/uac/oauth/token
#      clientId: sofmit-client
#      clientSecret: sofmit_secret
#      clientAuthenticationScheme: header
#      scope: select
#    resource:
#      user-info-uri: http://localhost:9000/uac/user
#management:
#  security:
#    enabled: false