spring:
  application:
    name: test
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: dev
  zipkin:
    base-url: http://localhost:9040
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
server:
  port: 9011
security:
  user:
    password: root
    name: root