server:
  port: 9003
spring:
  application:
    name: sunshine-provider-pmc
  redis:
    host: 127.0.0.2
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
security:
  oauth2:
    client:
      clientId: admin
      clientSecret: 123456
      access-token-uri: http://localhost:9000/uac/oauth/token
      user-authorization-uri: http://localhost:9000/uac/oauth/authorize
    resource:
      user-info-uri: http://localhost:9000/uac/user